//
// Generated file, do not edit! Created by nedtool 5.6 from lab061Msg.msg.
//

#ifndef __LAB061MSG_M_H
#define __LAB061MSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>lab061Msg.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message lab061Msg
 * {
 *     int id;
 * 
 *     double timeSent;
 *     double timeArrvived;
 * }
 * </pre>
 */
class lab061Msg : public ::omnetpp::cMessage
{
  protected:
    int id;
    double timeSent;
    double timeArrvived;

  private:
    void copy(const lab061Msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const lab061Msg&);

  public:
    lab061Msg(const char *name=nullptr, short kind=0);
    lab061Msg(const lab061Msg& other);
    virtual ~lab061Msg();
    lab061Msg& operator=(const lab061Msg& other);
    virtual lab061Msg *dup() const override {return new lab061Msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual double getTimeSent() const;
    virtual void setTimeSent(double timeSent);
    virtual double getTimeArrvived() const;
    virtual void setTimeArrvived(double timeArrvived);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const lab061Msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, lab061Msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LAB061MSG_M_H

